### PR TITLE
An underflow meant that for first windowsSize values, no search was d…

### PR DESCRIPTION
**Pull request by DanielNaro**
### Description of the Change

The algorithm for match coding works on a window prior to the current position. In order to calculate the position where the window starts, the size is substracted from the current position. Due to the language (C++) and the variable type (unsigned) this means that there is an underflow, leading to negative numbers interpreted as very big numbers. As the for loop stops at the current position, this could not produce segmentation faults.
The change makes sure that no underflow will occur, otherwise the window start is set to 0.

### Benefits

This change ensures that it is possible to find matches for the positions having an index smaller than window size.

### Possible Drawbacks

This modification will very slightly increase the computation time.

### Applicable Issues

This does not solve a bug, nor any issue, it only ensures that a little bit more compression through encoding can be gained.

### CODE REVIEW

**Comment by DanielNaro** [comment]
I now see that a second commit, which I intended to be for another pull request is also included here. The second commit has nothing to do with the current pull request, and I am less confident about.

**Comment by voges** [comment]
Hi Daniel,
Thanks for the match coding improvement! I'd be ready to pull that commit. Regarding your second commit, that one looks a bit suspicious to me... ;) Can you elaborate on that one?
Best,
Jan

**Comment by DanielNaro** [comment]
Hi Jan,
yes, the second one is stranger, and only happened to me while debugging. The constructor for OutputFile calls the constructor for File, which calls the open method. This means that after calling the constructor of the super class, the pointer called m_fp is set. However, then within the body of the OutputFile constructor, the open method is called again, and the assert checking that m_fp is not set fails.
My suspicion is that the assert is not compiled in release, therefore it only fails in debug.
Regards,
Daniel

**Comment by voges** [comment]
Hi Daniel,
I double-checked: the open() call in the OutputFile constructor is superfluous. You were right. :)
Best,
Jan

**Review by voges — APPROVED** [review]
Looks good, thanks!

**Comment by tparidae** [comment]
Well spotted. It used to be checked at a certain point in time but this got lost apparently.

Thanks

**Pull request merged**
